### ISSUE TITLE
Rumour Pity Rate

### ISSUE THREAD

**Issue by Dyliotic** [geel9/runelite-hunter-rumours#16]
Forwarding my request to an issue here as suggested by DapperMickie

>

While doing rumours the only thing I am currently missing is some sort of action counter till pity rate has been achieved.

For example, I am on an orange salamander task. I know the drop rate is 1/25, and that if I do not receive the drop at action 45, I will get the pity drop at 46 because I have the full outfit.

Maybe a small window that says something like: "Hunter NPC Icon" "Currently Caught Number"/"Pity Rate According to Hunter Outfit equipped" or "Orange Salamander 45/46".

**Comment by DapperMickie** [comment]
Fixed by geel9 in https://github.com/geel9/runelite-hunter-rumours/commit/18ef00b2d11b6e85826fcf6b094e6332b90d8879
Will come out next update!
