### ISSUE TITLE
Change text overlay on infobox to current rumour

### ISSUE THREAD

**Issue by MrDarkSide76** [geel9/runelite-hunter-rumours#27]
Currently it just has the word Rumour hovering over it. I think it would be better if it was a short form of what your current rumour is:

SM Sunlight Moth
MM Moonlight Moth
BW Black Warlock
SK Snowy Knight
SG Sapphire Glacialis

SA Sunlight Antelope
MA Moonlight Antelope

DK Dashing Kebbit
DK Dark Kebbit
SK Spotted Kebbit
WK Wild Kebbit
BK Barb-tailed Kebbit
SK Sabre-toothed Kebbit
RK Razor-backed Kebbit
PK Prickly Kebbit

RS Red Salamander
OS Orange Salamander
TS Tecu Salamander
SL Swamp Lizard

GC Grey Chinchompa
RC Red Chinchompa
PF Pyre Fox
EJ Embertailed Jerboa

H Herbiboar

TW Tropical Wagtail

SL Spined Larupia
HG Horned Graahk
SK Sabre-toothed Kyatt

**Comment by DapperMickie** [comment]
We changed this to display the kc left until you hit the pity rate, thanks for the suggestion though.

**Comment by DapperMickie** [comment]
The pity rate update has come out so I'm closing this issue.
