### ISSUE TITLE
Pity Rate Appears Off

### ISSUE THREAD

**Issue by apa20211** [geel9/runelite-hunter-rumours#39]
I've been doing Hunter Rumors for a while and after comparing with the pity rates we have available on the [wiki](https://oldschool.runescape.wiki/w/Hunters%27_Rumours#Drop_rates), I think there's still some rounding issues going on. Every time I get to the pity rate, it ends at 12 instead of 13. The formula from below is returning 13 after rounding down.
![image](https://github.com/geel9/runelite-hunter-rumours/assets/103959802/b7dba8f2-cf36-4410-933d-ff894f5958f6)
https://github.com/geel9/runelite-hunter-rumours/blob/08d73975f8ffd9eb866d16fbb04441e8df1cbc47/src/main/java/com/geel/hunterrumours/enums/Trap.java#L28-L30

I'm not sure if this extends to other drop rates as well, but just my findings.

**Comment by DapperMickie** [comment]
I will look into it, how many items are you wearing?

**Comment by apa20211** [comment]
> I will look into it, how many items of the outfit are you wearing (and which ones) and when have you last restarted the client?

I have full outfit (and max cape, I don't think this matters either but is worth mentioning I suppose).

I restart every wednesday
