### ISSUE TITLE
Catch rate showing incorrectly

### ISSUE THREAD

**Issue by pblcnme** [geel9/runelite-hunter-rumours#43]
After quite a few hunts the catch rate seemed to quit showing correctly and just keeps adding on to the caught rate
![image](https://github.com/geel9/runelite-hunter-rumours/assets/171295214/af2f013e-19c3-4fc1-865d-7e072ed66dfb)

**Comment by pblcnme** [comment]
i've been using different masters. right now I'm using the beginner trying to set up block list

**Comment by DapperMickie** [comment]
Yeah we're aware of the issue, this is a duplicate of https://github.com/geel9/runelite-hunter-rumours/issues/42 and https://github.com/geel9/runelite-hunter-rumours/issues/40 . This has been fixed, we're just working on some other things before updating the plugin. As soon as you'll do any of the other masters, it'll reset.

**Comment by pblcnme** [comment]
Awesome Thank you!
