### ISSUE TITLE
Midway percentage unreadable

### ISSUE THREAD

**Issue by pudding437** [geel9/runelite-hunter-rumours#48]
When a hunter rumour is completed, and the End-of-rumour Message option is selected, I find that the percantage is nearly completely unreadable.  Would it be possible to change the midway percentage colour to orange instead so that there is a greater contrast.

![image](https://github.com/geel9/runelite-hunter-rumours/assets/89750770/30f29355-052e-4927-ac6a-b3b4758c21e3)

**Comment by DapperMickie** [comment]
We'll most likely add this to our next release of the plugin, I made most (if not all) currently unconfigurable colors configurable.
